const Colours = {
    Primary: '#8cc544',
    PrimaryDark: '#89bd13',  
    appBack: '#eeeeee',
    searchBack: '#e8eff7',
    LeanBack: '#fce2ed',
    LeanText: '#f368a3',
    seaBack: '#d9e8ff',
    seaText: '#6799f7',
    vegBack: '#b2eadf',
    vegText: '#12a680',
    fruitsBack: '#ffd5d6',
    fruitsText: '#f96565',
    alterBack: '#fceed3',
    alterText: '#ffcb5e',
    sauceBack: '#feeecc',
    sauceText: '#ec5254',
    textColour:'#262626',
    active: '#12a680',
    inactive: '#ec5254',
    white:'#ffffff',
    border:'#e8e8e8',
    
    TextPrimary: '#fff',
    TextPrimarySemiDark: '#e1e1e1',
    TextPrimarySemiMoreDark: '#a0a0a0',
    TextPrimaryDark: '#000',
}

export { Colours };